# Generated by Django 4.0.3 on 2022-05-31 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
