# Generated by Django 4.0.3 on 2022-05-31 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faceExpressions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='nom')),
                ('last_name', models.CharField(max_length=200, verbose_name='prenom')),
                ('adress', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('photo_file_name', models.ImageField(upload_to='', verbose_name='photo')),
                ('cv_file_name', models.FileField(upload_to='cv')),
                ('video_file_name', models.FileField(upload_to='videos')),
                ('selected', models.BooleanField(default=False)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('angry', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('disgust', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('fear', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('surprise', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('naturel', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('sad', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('happy', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
            ],
        ),
        migrations.CreateModel(
            name='Postes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste_type', models.CharField(max_length=200)),
                ('poste_description', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Videos',
        ),
        migrations.AddField(
            model_name='candidats',
            name='poste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poste', to='faceExpressions.postes'),
        ),
    ]
